#!/usr/bin/env python3
"""Generate the launcher icons for 云枢 (Air Gesture Hub).

Run from the workspace root:

    .venv\\Scripts\\python.exe android\\tools\\make_icons.py

Source artwork: android/tools/icon-source.jpg (1280x1280, light-blue background).
Everything is derived from that one file, so regenerating after an artwork change
is a single command.

Why this script exists (instead of hand-made PNGs):
  * an adaptive icon needs a *foreground* whose content sits inside the 66/108
    safe zone, otherwise the launcher mask eats the tablet/hand;
  * the legacy icon needs 5 densities plus a round variant;
  * all of that has to be reproducible when the artwork is replaced.

Outputs (all under app/src/main/res):
    mipmap-{m,h,xh,xxh,xxxh}dpi/ic_launcher.png             legacy, full bleed
    mipmap-{m,h,xh,xxh,xxxh}dpi/ic_launcher_round.png       legacy, circular
    mipmap-{m,h,xh,xxh,xxxh}dpi/ic_launcher_foreground.png  adaptive foreground
    mipmap-anydpi-v26/ic_launcher.xml, ic_launcher_round.xml
    values/colors.xml                                       adaptive background

Console output is ASCII-only on purpose: this project has been burned by the
Windows console codepage mangling Chinese text in build tooling.
"""
import os
import sys

from PIL import Image, ImageDraw

HERE = os.path.dirname(os.path.abspath(__file__))
DEFAULT_SRC = os.path.join(HERE, 'icon-source.jpg')
RES = os.path.abspath(os.path.join(HERE, '..', 'app', 'src', 'main', 'res'))

# 48dp legacy icon at each density
LEGACY = {'mdpi': 48, 'hdpi': 72, 'xhdpi': 96, 'xxhdpi': 144, 'xxxhdpi': 192}
# 108dp adaptive-icon layer at each density
FORE = {'mdpi': 108, 'hdpi': 162, 'xhdpi': 216, 'xxhdpi': 324, 'xxxhdpi': 432}

# How much of the 108dp canvas the artwork occupies in the adaptive foreground.
# The guaranteed-visible zone is the middle 66/108 (61%); the artwork's subject
# spans ~78% of the source, so 0.75 puts the subject at ~59% -> safely inside,
# while the far end of the forearm still reaches the mask edge (user accepted
# that cropping: "我重新给你发一张允许裁切").
FORE_SCALE = 0.75


def write_png(img, folder, name):
    d = os.path.join(RES, folder)
    os.makedirs(d, exist_ok=True)
    path = os.path.join(d, name)
    img.save(path, 'PNG', optimize=True)
    return path


def main():
    src = sys.argv[1] if len(sys.argv) > 1 else DEFAULT_SRC
    im = Image.open(src).convert('RGB')
    w, h = im.size
    # Flat background: the top-left corner pixel *is* the background colour.
    bg = im.getpixel((2, 2))
    print('source   : %s (%dx%d)' % (src, w, h))
    print('bg colour: #%02X%02X%02X' % bg)

    for dens, px in LEGACY.items():
        write_png(im.resize((px, px), Image.LANCZOS), 'mipmap-' + dens, 'ic_launcher.png')

        # Round variant: supersample an elliptical alpha mask so the edge is smooth.
        rnd = im.resize((px, px), Image.LANCZOS).convert('RGBA')
        mask = Image.new('L', (px * 4, px * 4), 0)
        ImageDraw.Draw(mask).ellipse((0, 0, px * 4 - 1, px * 4 - 1), fill=255)
        rnd.putalpha(mask.resize((px, px), Image.LANCZOS))
        write_png(rnd, 'mipmap-' + dens, 'ic_launcher_round.png')

    for dens, px in FORE.items():
        canvas = Image.new('RGBA', (px, px), (0, 0, 0, 0))
        inner = int(round(px * FORE_SCALE))
        art = im.resize((inner, inner), Image.LANCZOS).convert('RGBA')
        off = (px - inner) // 2
        canvas.paste(art, (off, off), art)
        write_png(canvas, 'mipmap-' + dens, 'ic_launcher_foreground.png')

    anydpi = os.path.join(RES, 'mipmap-anydpi-v26')
    os.makedirs(anydpi, exist_ok=True)
    adaptive = (
        '<?xml version="1.0" encoding="utf-8"?>\n'
        '<!-- Generated by android/tools/make_icons.py - do not edit by hand. -->\n'
        '<adaptive-icon xmlns:android="http://schemas.android.com/apk/res/android">\n'
        '    <background android:drawable="@color/ic_launcher_background" />\n'
        '    <foreground android:drawable="@mipmap/ic_launcher_foreground" />\n'
        '</adaptive-icon>\n'
    )
    for name in ('ic_launcher.xml', 'ic_launcher_round.xml'):
        with open(os.path.join(anydpi, name), 'w', encoding='utf-8') as f:
            f.write(adaptive)

    values = os.path.join(RES, 'values')
    os.makedirs(values, exist_ok=True)
    with open(os.path.join(values, 'colors.xml'), 'w', encoding='utf-8') as f:
        f.write(
            '<?xml version="1.0" encoding="utf-8"?>\n'
            '<resources>\n'
            '    <!-- 自适应图标的背景层：取样自原图角落底色，保证前景与背景无缝。\n'
            '         Generated by android/tools/make_icons.py -->\n'
            '    <color name="ic_launcher_background">#%02X%02X%02X</color>\n'
            '</resources>\n' % bg
        )

    print('written  : mipmap-{m,h,xh,xxh,xxxh}dpi (legacy + round + adaptive foreground)')
    print('written  : mipmap-anydpi-v26/ic_launcher{,_round}.xml, values/colors.xml')


if __name__ == '__main__':
    main()
